    version: '2'
    services:
        loadbalance:
             build: .
             ports:
                - "81:80"
                
        tomcat1:
             build: ./tomcat
             ports:
                - "82:8080"

        tomcat2:
             build: ./tomcat
             ports:
                - "83:8080"

        tomcat3:
             build: ./tomcat
             ports:
                - "84:8080"
