    version: '2'
    services:
        loadbalance:
             build: .
             ports:
                - "81:80"
                
        tomcat1:
             build: ./tomcat
             ports:
                - "82:8080"
             volumes: 
                - /home/vagrant/data/static1/:/usr/local/static
                - /home/vagrant/data/webapps/:/opt/apache-tomcat-7.0.69/webapps

        tomcat2:
             build: ./tomcat
             ports:
                - "83:8080"
             volumes:   
                - /home/vagrant/data/static2/:/usr/local/static
                - /home/vagrant/data/webapps2/:/opt/apache-tomcat-7.0.69/webapps

        tomcat3:
             build: ./tomcat
             ports:
                - "84:8080"
             volumes:
                - /home/vagrant/data/static3/:/usr/local/static
                - /home/vagrant/data/webapps2/:/opt/apache-tomcat-7.0.69/webapps
